// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTtRONo2Dbysev-MHTXwUf2ko0ogicT-o',
    appId: '1:48959489246:web:55d4f546e449b866d82e4f',
    messagingSenderId: '48959489246',
    projectId: 'tship-f258c',
    authDomain: 'tship-f258c.firebaseapp.com',
    storageBucket: 'tship-f258c.appspot.com',
    measurementId: 'G-143Y6VSXRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2XvxeCZCujsybuu9KiVkK3oTNYGW5aOE',
    appId: '1:48959489246:android:59522672a2518faed82e4f',
    messagingSenderId: '48959489246',
    projectId: 'tship-f258c',
    storageBucket: 'tship-f258c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3V-g8iUsKry_5JBP3ygX_8ZP1HwqyvcQ',
    appId: '1:48959489246:ios:16e91d739192edf7d82e4f',
    messagingSenderId: '48959489246',
    projectId: 'tship-f258c',
    storageBucket: 'tship-f258c.appspot.com',
    iosBundleId: 'com.example.shoppizel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3V-g8iUsKry_5JBP3ygX_8ZP1HwqyvcQ',
    appId: '1:48959489246:ios:16e91d739192edf7d82e4f',
    messagingSenderId: '48959489246',
    projectId: 'tship-f258c',
    storageBucket: 'tship-f258c.appspot.com',
    iosBundleId: 'com.example.shoppizel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTtRONo2Dbysev-MHTXwUf2ko0ogicT-o',
    appId: '1:48959489246:web:275223107a210bb1d82e4f',
    messagingSenderId: '48959489246',
    projectId: 'tship-f258c',
    authDomain: 'tship-f258c.firebaseapp.com',
    storageBucket: 'tship-f258c.appspot.com',
    measurementId: 'G-Q97958P4R2',
  );
}
